# Generated by Django 2.1.4 on 2020-03-21 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
